version: "3.8"
services:
  now-waypoint-mysql:
    build: ./now-waypoint-mysql
    image: now-waypoint-mysql:5.0.0-compose
    ports:
      - "3306:3306"
    volumes:
      - mydata:/var/lib/mysql
      - ./now-waypoint-mysql/init:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
    restart: always

  now-waypoint-core:
    build: ./now-waypoint-core
    image: now-waypoint-core:5.0.0-compose
    ports:
      - "8080:8080"
    environment:
      - DB_URL=now-waypoint-mysql
      - DB_PORT=3306
      - DB_NAME=nwpdb
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
    depends_on:
      - now-waypoint-mysql
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 512M
    restart: on-failure

volumes:
  mydata:
