name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            docker pull immyeong/now-waypoint-mysql:${{ github.sha }}
            docker pull immyeong/now-waypoint-core:${{ github.sha }}
            docker pull redis:latest
            sudo sed -i 's/immyeong\/now-waypoint-mysql:latest/immyeong\/now-waypoint-mysql:${{ github.sha }}/' docker-compose.yml
            sudo sed -i 's/immyeong\/now-waypoint-core:latest/immyeong\/now-waypoint-core:${{ github.sha }}/' docker-compose.yml
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker image prune -f
