name: Deploy to EC2

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Core SHA file
        uses: actions/download-artifact@v2
        with:
          name: core_sha
          path: .

      - name: Download MySQL SHA file
        uses: actions/download-artifact@v2
        with:
          name: mysql_sha
          path: .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            export CORE_SHA=$(cat core_sha.txt)
            export MYSQL_SHA=$(cat mysql_sha.txt)
            sudo sed -i "s/immyeong\/now-waypoint-mysql:.*/immyeong\/now-waypoint-mysql:${MYSQL_SHA}/" docker-compose.yml
            sudo sed -i "s/immyeong\/now-waypoint-core:.*/immyeong\/now-waypoint-core:${CORE_SHA}/" docker-compose.yml
            sudo docker-compose down --remove-orphans
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker image prune -f
